WITH RECURSIVE CTE
AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.GEN+1
    FROM ECOLI_DATA AS E
    JOIN CTE AS C
    ON C.ID = E.PARENT_ID
)

SELECT ID
FROM CTE
WHERE CTE.GEN = 3
ORDER BY ID;