SELECT T.ITEM_ID,
       I.ITEM_NAME,
       I.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS I
ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE AS T2
    WHERE T.ITEM_ID = T2.PARENT_ITEM_ID
)
ORDER BY T.ITEM_ID DESC;
