WITH AVAILABLE_CARS AS (
    SELECT CAR_ID,
           CAR_TYPE,
           DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
    )
)

SELECT A.CAR_ID,
       A.CAR_TYPE,
       FLOOR(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM AVAILABLE_CARS AS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON A.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = '30일 이상'
AND FLOOR(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) >= 500000 
AND FLOOR(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;