SELECT ID,
        CASE
            WHEN (ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) * 100) / (COUNT(SIZE_OF_COLONY) OVER()) <= 25 THEN 'CRITICAL'
            WHEN (ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) * 100) / (COUNT(SIZE_OF_COLONY) OVER()) <= 50 THEN 'HIGH'
            WHEN (ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) * 100) / (COUNT(SIZE_OF_COLONY) OVER()) <= 75 THEN 'MEDIUM'
            WHEN (ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) * 100) / (COUNT(SIZE_OF_COLONY) OVER()) <= 100 THEN 'LOW'
            ELSE NULL
        END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;