SELECT RI.REST_ID, 
       REST_NAME, 
       FOOD_TYPE, 
       FAVORITES, 
       ADDRESS, 
       ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS RI
    JOIN REST_REVIEW AS RR
    ON RR.REST_ID = RI.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;