WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.GEN+1
    FROM ECOLI_DATA AS E
    JOIN CTE AS C
    ON E.PARENT_ID = C.ID
)

SELECT COUNT(*) AS 'COUNT',
       C.GEN AS 'GENERATION'
FROM ECOLI_DATA AS E
JOIN CTE AS C
ON E.ID = C.ID
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA AS EE
    WHERE EE.PARENT_ID = C.ID
)
GROUP BY C.GEN
ORDER BY C.GEN