SELECT O.PRODUCT_ID,
       PRODUCT_NAME,
       SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_ORDER AS O
JOIN FOOD_PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;