WITH T AS (
    SELECT F.FLAVOR,
           SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF AS F
    JOIN JULY AS J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY FLAVOR
    ORDER BY TOTAL DESC
)

SELECT FLAVOR
FROM T
LIMIT 3;

# SELECT *
# FROM JULY