WITH REVIEW_CNT AS (
    SELECT MP.MEMBER_ID,
           COUNT(*) AS CNT
    FROM MEMBER_PROFILE AS MP
    JOIN REST_REVIEW AS RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY MEMBER_ID
),
CNT_MAX AS (
    SELECT MEMBER_ID
    FROM REVIEW_CNT
    WHERE CNT = (SELECT MAX(CNT) FROM REVIEW_CNT)
)

SELECT MEMBER_NAME,
       REVIEW_TEXT,
       DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS P
ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID FROM CNT_MAX)
ORDER BY REVIEW_DATE, REVIEW_TEXT;