WITH ONLY AS (
    SELECT MP.MEMBER_ID,
           MEMBER_NAME,
           COUNT(*)
    FROM MEMBER_PROFILE AS MP
    JOIN REST_REVIEW AS RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT MEMBER_NAME,
       REVIEW_TEXT,
       DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS P
ON R.MEMBER_ID = P.MEMBER_ID
WHERE (P.MEMBER_NAME) IN (
    SELECT MEMBER_NAME
    FROM ONLY
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;