SELECT SUM(SCORE) AS SCORE,
       HE.EMP_NO,
       HE.EMP_NAME,
       HE.POSITION,
       HE.EMAIL
FROM HR_EMPLOYEES AS HE
JOIN HR_GRADE AS HG
ON HE.EMP_NO = HG.EMP_NO
GROUP BY HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
ORDER BY SCORE DESC
LIMIT 1;


# GROUP BY EMP_NO
# ORDER BY SUM(SCORE) DESC
# LIMIT 1