SELECT TITLE, UR.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID, UR.CONTENTS, DATE_FORMAT(UR.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_REPLY UR
    JOIN  USED_GOODS_BOARD UB
    ON UB.BOARD_ID = UR.BOARD_ID
WHERE UB.CREATED_DATE LIKE '2022-10%'
ORDER BY UR.CREATED_DATE, TITLE;